# Generated by Django 4.1.7 on 2023-03-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Complete'), (5, 'Cancel'), (6, 'Certified'), (7, 'Ongoing')])),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=250)),
                ('short_description', models.CharField(max_length=30)),
                ('long_description', models.TextField()),
                ('club', models.CharField(max_length=70)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('messages', models.JSONField(blank=True, null=True)),
                ('hod_verified', models.BooleanField(default=False)),
                ('dean_verified', models.BooleanField(default=False)),
                ('vc_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
