# Generated by Django 4.1.7 on 2023-09-07 15:02

from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Displayed'), (3, 'Completed'), (4, 'Report Submitted'), (5, 'Report Approved'), (6, 'Certified')], default=1)),
                ('accepted_role', models.JSONField(default=event.models.default_accepted_role)),
                ('total_strength', models.PositiveIntegerField(blank=True, null=True)),
                ('fcfs', models.BooleanField(default=True)),
                ('image', models.ImageField(max_length=500, upload_to='poster/')),
                ('title', models.CharField(max_length=250)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('club', models.CharField(max_length=70)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='', validators=[event.models.FileToLarge])),
                ('history', models.JSONField(blank=True, null=True)),
                ('hod_verified', models.BooleanField(default=False)),
                ('dean_verified', models.BooleanField(default=False)),
                ('vc_verified', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('report_verified', models.BooleanField(default=False)),
                ('require_number', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Declined'), ('2', 'Applied'), ('3', 'Accepted')], default='2', max_length=1)),
                ('owner', models.BooleanField(default=False)),
                ('organizer', models.BooleanField(default=False)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=event.models.event_certificate_upload_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
