# Generated by Django 4.1.7 on 2023-03-10 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_alter_event_date_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(limit_choices_to={'role__in': [0, 1, 2]}, to=settings.AUTH_USER_MODEL),
        ),
    ]
