# Generated by Django 4.1.7 on 2023-03-12 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_event_participant_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(limit_choices_to={'role__in': [0, 1, 2]}, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
