# Generated by Django 4.1.7 on 2023-03-14 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0010_club_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': [0, 1, 2]}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Completed'), (5, 'Cancel'), (6, 'Certified'), (7, 'Ongoing')], default=1),
        ),
    ]
