# Generated by Django 4.1.7 on 2023-03-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_event_organizer_alter_event_owner_participant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Organizer',
            new_name='organizer',
        ),
    ]
