# Generated by Django 4.1.7 on 2023-03-31 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_alter_user_joining_year_alter_user_leaving_year'),
        ('event', '0015_remove_participant_members_remove_event_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='applied_participant',
            field=models.ManyToManyField(related_name='applied_participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='branch',
            field=models.ManyToManyField(blank=True, to='user.branch'),
        ),
    ]
