# Generated by Django 4.1.7 on 2023-03-31 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0016_event_applied_participant_alter_event_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='applied_participant',
            field=models.ManyToManyField(blank=True, related_name='applied_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
