# Generated by Django 4.1.7 on 2023-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_alter_event_applied_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fcfs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_strength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
