# Generated by Django 4.1.7 on 2023-04-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_remove_event_accpted_role_event_accpted_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='accpted_role',
            new_name='accepted_role',
        ),
    ]
