# Generated by Django 4.1.7 on 2023-04-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_rename_accpted_role_event_accepted_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_number',
            field=models.BooleanField(default=False),
        ),
    ]
