# Generated by Django 4.1.7 on 2023-04-08 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0024_event_require_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accepted_participant',
        ),
        migrations.RemoveField(
            model_name='event',
            name='applied_participant',
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Declined'), ('1', 'Applied'), ('2', 'Accepted')], max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', through='event.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
