# Generated by Django 4.1.7 on 2023-04-08 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0025_remove_event_accepted_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, through='event.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
