# Generated by Django 4.1.7 on 2023-04-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_remove_event_organizer_remove_event_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('0', 'Not Applicable'), ('1', 'Declined'), ('2', 'Applied'), ('3', 'Accepted')], default='2', max_length=1),
        ),
    ]
