# Generated by Django 4.1.7 on 2023-04-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_alter_eventparticipant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='messages',
            new_name='history',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Displayed'), (5, 'Completed'), (6, 'Report Submitted'), (7, 'Report Approved'), (8, 'Certified'), (9, 'Canceled')], default=1),
        ),
    ]
