# Generated by Django 4.1.7 on 2023-05-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
