# Generated by Django 4.1.7 on 2023-05-23 20:11

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_event_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[event.models.FileToLarge]),
        ),
        migrations.AddField(
            model_name='event',
            name='report_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.event_certificate_upload_path),
        ),
    ]
