# Generated by Django 4.1.7 on 2023-03-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Register/Emp Number'),
        ),
    ]
