# Generated by Django 4.1.7 on 2023-03-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_role_alter_branch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='batch_end_date',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='batch_start_date',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
    ]
