# Generated by Django 4.1.7 on 2023-03-29 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_branch_batch_end_date_branch_batch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joining_year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='leaving_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950)]),
        ),
    ]
