# Generated by Django 4.1.7 on 2023-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_joining_year_alter_user_leaving_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
