# Generated by Django 4.1.7 on 2023-05-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_forgot_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forgot_otp',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
