# Generated by Django 4.1.7 on 2023-09-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_forgot_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joining_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leaving_year',
        ),
    ]
